apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: jettison-ui-integration-test
  namespace: jettisonproj
spec:
  args:
  - name: service-name
  metrics:
  - name: jettison-ui-integration-test
    provider:
      job:
        spec:
          backoffLimit: 1
          activeDeadlineSeconds: 600
          template:
            spec:
              containers:
              - name: jettison-ui-integration-test
                image: ghcr.io/jettisonproj/jettison-ui-integration-test:271e096b3c6e4599d700862abbd709e527ac7a44
                args:
                - "./integration-test.sh"
                - "http://{{args.service-name}}"
              restartPolicy: Never
