apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: jettison-ui-integration-test
  namespace: jettisonproj
spec:
  args:
  - name: service-name
  metrics:
  - name: jettison-ui-integration-test
    provider:
      job:
        spec:
          backoffLimit: 1
          activeDeadlineSeconds: 600
          template:
            spec:
              containers:
              - name: jettison-ui-integration-test
                image: ghcr.io/jettisonproj/jettison-ui-integration-test:c37bf18b448ebf1519155cf31bfae841f1d92964
                args:
                - "./integration-test.sh"
                - "http://{{args.service-name}}"
              restartPolicy: Never
