apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  # Ensure a short name is used
  # See https://github.com/argoproj/argo-rollouts/issues/795
  name: jettison-ui-e2e-test
  namespace: jettisonproj
spec:
  args:
  - name: service-name
  metrics:
  - name: jettison-ui-e2e-test
    provider:
      job:
        spec:
          backoffLimit: 1
          activeDeadlineSeconds: 600
          template:
            spec:
              containers:
              - name: jettison-ui-e2e-test
                image: ghcr.io/jettisonproj/jettison-ui-integration-test:596074ff7f2d406bc50a0298dd79f92d580643cb
                args:
                - "./integration-test.sh"
                - "http://{{args.service-name}}"
              restartPolicy: Never
