apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  # Ensure a short name is used
  # See https://github.com/argoproj/argo-rollouts/issues/795
  name: jettison-ui-e2e-test
  namespace: jettisonproj
spec:
  args:
  - name: service-name
  metrics:
  - name: jettison-ui-e2e-test
    provider:
      job:
        spec:
          backoffLimit: 1
          activeDeadlineSeconds: 600
          template:
            metadata:
              labels:
                app: jettison-ui-e2e-test
            spec:
              containers:
              - name: jettison-ui-e2e-test
                image: ghcr.io/jettisonproj/jettison-ui-integration-test:9e538fd4d751339848c53d94d6632cfae58904c9
                env:
                - name: PLAYWRIGHT_BASE_URL
                  value: "http://{{args.service-name}}"
                - name: CI
                  value: "true"
              restartPolicy: Never
