apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  # Ensure a short name is used
  # See https://github.com/argoproj/argo-rollouts/issues/795
  name: jettison-ui-e2e-test
  namespace: jettisonproj
spec:
  args:
  - name: service-name
  metrics:
  - name: jettison-ui-e2e-test
    provider:
      job:
        spec:
          backoffLimit: 1
          activeDeadlineSeconds: 600
          template:
            spec:
              containers:
              - name: jettison-ui-e2e-test
                image: ghcr.io/jettisonproj/jettison-ui-integration-test:1d865e46df1c6f09abd3b24792f88a277eb5247d
                env:
                - name: PLAYWRIGHT_BASE_URL
                  value: "http://{{args.service-name}}"
                - name: CI
                  value: "true"
              restartPolicy: Never
