apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: jettisonproj
  name: jettison-api-e2e-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jettison-api-e2e-role
subjects:
- kind: ServiceAccount
  name: jettison-api-e2e-sa
