apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jettison-api-e2e-cluster-role
rules:
# Validates cluster workflow template creation
- apiGroups:
  - argoproj.io
  resources:
  - clusterworkflowtemplates
  verbs:
  - get
  - list
  - watch
